#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

mkdir -p /tmp

clear
echo -e "\033[1;32m======================================"
echo "      WELCOME TO NIB LINUX          "
echo "    The monster is officially ALIVE "
echo -e "======================================\033[0m"

ip link set eth0 up
udhcpc -i eth0 -q -s /usr/share/udhcpc/default.script
echo "nameserver 8.8.8.8" > /etc/resolv.conf

exec /bin/sh
